name 'trusted_ca'
maintainer 'Dan Clough'
maintainer_email 'dan@clough.xyz'
license 'Apache-2.0'
description 'Installs trusted CA certificates from a data bag'
version '1.0.0'
chef_version '>= 14.0'
depends 'trusted_certificate'
issues_url 'https://github.com/danclough/chef-trusted_ca/issues'
source_url 'https://github.com/danclough/chef-trusted_ca'
